# Generated by Django 3.2.21 on 2023-11-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_average_rating'),
        ('saved_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='books.book'),
        ),
    ]
