# Generated by Django 3.2.21 on 2023-10-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20231001_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='average_rating',
        ),
    ]
